### ISSUE TITLE
[Arsenal] Game crashes when the anchor or scythe are rendered on someone else's back

### ISSUE THREAD

**Issue by r1sk01** [doctor4t/Issues#33]
Minecraft version: 1.20.1
Fabric version: 0.16.9
Mod version: 0.1.1

The crash report for both states that the classes "`dev.doctor4t.arsenal.client.render.item.ScytheDynamicItemRenderer.render`" and "`dev.doctor4t.arsenal.client.render.item.AnchorbladeDynamicItemRenderer.render`" cause the crashes, particularly on the lines that use the following:
```java
((class_4597.class_4598)vertexConsumers).method_22993();
```
Both creating the error "`java.lang.ClassCastException: class net.minecraft.class_4618 cannot be cast to class net.minecraft.class_4597$class_4598 (net.minecraft.class_4618 and net.minecraft.class_4597$class_4598 are in unnamed module of loader 'knot' @4f7d0008)`".

Stacktrace 1 (Anchorblade):
```error
java.lang.ClassCastException: class net.minecraft.class_4618 cannot be cast to class net.minecraft.class_4597$class_4598 (net.minecraft.class_4618 and net.minecraft.class_4597$class_4598 are in unnamed module of loader 'knot' @4f7d0008)
at knot//dev.doctor4t.arsenal.client.render.item.AnchorbladeDynamicItemRenderer.render(AnchorbladeDynamicItemRenderer.java:73)
at knot//net.minecraft.class_756.handler$dlk000$fabric-rendering-v1$fabric_onRender(class_756.java:1041)
at knot//net.minecraft.class_756.method_3166(class_756.java)
at knot//net.minecraft.class_918.redirect$edl000$geckolib$cancelRender(class_918.java:3535)
at knot//net.minecraft.class_918.method_23179(class_918.java:126)
at knot//net.minecraft.class_918.method_23177(class_918.java:271)
at knot//net.minecraft.class_759.method_3233(class_759.java:164)
at knot//net.minecraft.class_989.method_4192(class_989.java:64)
at knot//net.minecraft.class_5697.method_4192(class_5697.java:35)
at knot//net.minecraft.class_989.method_17162(class_989.java:42)
at knot//net.minecraft.class_989.method_4199(class_989.java:15)
at knot//net.minecraft.class_922.method_4054(class_922.java:145)
at knot//net.minecraft.class_1007.method_4215(class_1007.java:66)
at knot//net.minecraft.class_1007.method_3936(class_1007.java:43)
at knot//net.minecraft.class_898.method_3954(class_898.java:145)
at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
at knot//net.minecraft.class_757.method_3192(class_757.java:880)
at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
at knot//net.minecraft.class_310.method_1514(class_310.java:802)
at knot//net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
Stacktrace 2 (Scythe):
```error
java.lang.ClassCastException: class net.minecraft.class_4618 cannot be cast to class net.minecraft.class_4597$class_4598 (net.minecraft.class_4618 and net.minecraft.class_4597$class_4598 are in unnamed module of loader 'knot' @4f7d0008)
	at knot//dev.doctor4t.arsenal.client.render.item.ScytheDynamicItemRenderer.render(ScytheDynamicItemRenderer.java:79)
	at knot//net.minecraft.class_756.handler$dlk000$fabric-rendering-v1$fabric_onRender(class_756.java:1041)
	at knot//net.minecraft.class_756.method_3166(class_756.java)
	at knot//net.minecraft.class_91[8](https://mclo.gs/OYuuDSZ#L8).redirect$edl000$geckolib$cancelRender(class_918.java:3535)
	at knot//net.minecraft.class_918.method_23179(class_918.java:126)
	at knot//net.minecraft.class_[9](https://mclo.gs/OYuuDSZ#L9)18.method_23177(class_918.java:271)
	at knot//dev.doctor4t.arsenal.client.render.feature.BackWeaponFeatureRenderer.render(BackWeaponFeatureRenderer.java:81)
	at knot//dev.doctor4t.arsenal.client.render.feature.BackWeaponFeatureRenderer.method_4199(BackWeaponFeatureRenderer.java:21)
	at knot//net.minecraft.class_922.method_4054(class_922.java:145)
	at knot//net.minecraft.class_[10](https://mclo.gs/OYuuDSZ#L10)07.method_4215(class_1007.java:66)
	at knot//net.minecraft.class_1007.method_3936(class_1007.java:43)
	at knot//net.minecraft.class_898.method_3954(class_898.java:145)
	at knot//net.minecraft.class_761.method_22977(class_761.java:1574)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1324)
	at knot//net.minecraft.class_757.method_3188(class_757.java:[11](https://mclo.gs/OYuuDSZ#L11)10)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:[12](https://mclo.gs/OYuuDSZ#L12)19)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by r1sk01** [comment]
found out theres newer versions of the mod, trying that out and seeing if its fixed

**Comment by r1sk01** [comment]
seems it may be fixed by a newer version of the mod, ill continue to monitor for a bit, see if its fixed
